alttracker/urls.py
from django.contrib import admin
from django.urls import include, path

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('wowprof/', include('wowprof.urls')),
    path('admin/', admin.site.urls),
    path('django-rq/', include('django_rq.urls')),
]

wowprof/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # path('test/',views.index,name='index'),
    path('', views.wowProfHome, name='wowprof_home'),
    path('redirect/', views.wowProfRedirect),
    # path('redirect/<str:codeState/', views.wowProfRedirect),
    # path('', views.calcHome,name='calc_home'),
    path('alts/', views.wowProfAlts, name='wowprof_alts'),
    path('alts/<str:name>/<str:realm>/profession/<str:profession>', views.wowProfAltsProfession, name='wowprof_alts_profession'),
    path('alts/<str:name>/<str:realm>/details', views.wowProfAltsMoreDetails, name='wowprof_alts_more'),
    path('requiem/', views.wowProfRequiem, name='wowprof_requiem'),
    path('checker/', views.wowProfChecker, name='wowprof_checker'),
    path('weekly/', views.wowProfWeekly, name='wowprof_weekly'),
    path('refresh_character/', views.refresh_character),
    # path('alts/export/', views.test_table, name='test_table'),
]

wowprof/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

# Create your models here.


class Alt(models.Model):
    altId = models.PositiveIntegerField(primary_key=True)
    altLevel = models.PositiveSmallIntegerField()
    altName = models.CharField(max_length=40)
    altRealm = models.CharField(max_length=40)
    altRealmId = models.PositiveSmallIntegerField()
    altRealmSlug = models.CharField(max_length=40)

    class AltClass(models.IntegerChoices):
        NO_CLASS = 0, _('No Class')
        WARRIOR = 1, _('Warrior')
        PALADIN = 2, _('Paladin')
        HUNTER = 3, _('Hunter')
        ROGUE = 4, _('Rogue')
        PRIEST = 5, _('Priest')
        DEATH_KNIGHT = 6, _('Death Knight')
        SHAMAN = 7, _('Shaman')
        MAGE = 8, _('Mage')
        WARLOCK = 9, _('Warlock')
        MONK = 10, _('Monk')
        DRUID = 11, _('Druid')
        DEMON_HUNTER = 12, _('Demon Hunter')
    altClass = models.PositiveSmallIntegerField(choices=AltClass.choices, default=AltClass.NO_CLASS)

    class AltRace(models.IntegerChoices):
        NO_RACE = 0, _('No Race')
        HUMAN = 1, _('Human')
        ORC = 2, _('Orc')
        DWARF = 3, _('Dwarf')
        NIGHT_ELF = 4, _('Night Elf')
        UNDEAD = 5, _('Undead')
        TAUREN = 6, _('Tauren')
        GNOME = 7, _('Gnome')
        TROLL = 8, _('Troll')
        GOBLIN = 9, _('Goblin')
        BLOOD_ELF = 10, _('Blood Elf')
        DRAENEI = 11, _('Draenei')
        WORGEN = 22, _('Worgen')
        PANDAREN_NEUTRAL = 24, _('Pandaren')
        PANDAREN_ALLIANCE = 25, _('Pandaren')
        PANDAREN_HORDE = 26, _('Pandaren')
        NIGHTBOURNE = 27, _('Nightbourne')
        HIGHMOUNTAIN_TAUREN = 28, _('Highmountain Tauren')
        VOID_ELF = 29, _('Void Elf')
        LIGHTFORGED_DRAENEI = 30, _('Lightforged Draenei')
        ZANDALARI_TROLL = 31, _('Zandalari Troll')
        KUL_TIRAN = 32, _('Kul Tiran')
        DARK_IRON_DWARF = 34, _('Dark Iron Dwarf')
        VULPERA = 35, _('Vulpera')
        MAGHAR_ORC = 36, _('Mag\'ar Orc')
        MECHAGNOME = 37, _('Mechagnome')
    altRace = models.PositiveSmallIntegerField(choices=AltRace.choices, default=AltRace.NO_RACE)

    altGender = models.CharField(max_length=6)
    altFaction = models.CharField(max_length=10)
    altExpiryDate = models.DateTimeField()

    class Meta:
        db_table = 'alttracker_alt'
        constraints = [
            models.UniqueConstraint(fields=['altName', 'altRealmSlug'], name='unique_alt')
        ]

    def __str__(self):
        return '%s - %s' % (self.altName, self.altRealm)


class AltCustom(models.Model):
    alt = models.OneToOneField(Alt, on_delete=models.CASCADE, primary_key=True)

    NOT_LEARNT = 0
    SLOW_GROUND = 1
    FAST_GROUND = 2
    SLOW_FLYING = 3
    FAST_FLYING = 4
    MOUNT = (
        (NOT_LEARNT, 'No Riding Skill'),
        (SLOW_GROUND, 'Slow Ground'),
        (FAST_GROUND, 'Fast Ground'),
        (SLOW_FLYING, 'Slow Flying'),
        (FAST_FLYING, 'Fast Flying'),
    )
    mount = models.PositiveSmallIntegerField(choices=MOUNT, default=SLOW_GROUND)

    LEVEL0 = 0
    LEVEL1 = 1
    LEVEL2 = 2
    LEVEL3 = 3
    GARRISON = (
        (LEVEL0, 'Not Built'),
        (LEVEL1, 'Level 1'),
        (LEVEL2, 'Level 2'),
        (LEVEL3, 'Level 3'),
    )
    garrison = models.PositiveSmallIntegerField(choices=GARRISON, default=LEVEL0)

    NO = 0
    YES = 1
    NA = 2
    MAGE_TOWER = (
        (NO, 'No'),
        (YES, 'Yes'),
        (NA, 'N/A'),
    )
    mageTower = models.PositiveSmallIntegerField(choices=MAGE_TOWER, default=NA)

    NO = 0
    YES = 1
    NA = 2
    NO_Q = 3
    SHADOWMOURNE = (
        (NO, 'No'),
        (YES, 'Yes'),
        (NA, 'N/A'),
        (NO_Q, 'Quest')
    )
    shadowmourne = models.PositiveSmallIntegerField(choices=SHADOWMOURNE, default=NA)

    # NO = 0
    # YES = 1
    # BALANCE_OF_POWER = (
    #     (NO, 'No'),
    #     (YES, 'Yes'),
    # )
    # balance_of_power = models.PositiveSmallIntegerField(choices=BALANCE_OF_POWER, default=NO)

    average_item_level = models.PositiveSmallIntegerField(default=0)

    class Profession(models.IntegerChoices):
        MISSING = 0, _('Missing')
        ALCHEMY = 171, _('Alchemy')
        BLACKSMITHING = 164, _('Blacksmithing')
        ENCHANTING = 333, _('Enchanting')
        ENGINEERING = 202, _('Engineering')
        INSCRIPTION = 773, _('Inscription')
        JEWELCRAFTING = 755, _('Jewelcrafting')
        LEATHERWORKING = 165, _('Leatherworking')
        TAILORING = 197, _('Tailoring')
        HERBALISM = 182, _('Herbalism')
        MINING = 186, _('Mining')
        SKINNING = 393, _('Skinning')
    profession1 = models.PositiveSmallIntegerField(choices=Profession.choices, default=Profession.MISSING)
    profession2 = models.PositiveSmallIntegerField(choices=Profession.choices, default=Profession.MISSING)

    location = models.CharField(max_length=100)
    gold = models.CharField(max_length=12)

    lastRefresh = models.DateTimeField()

    class Meta:
        db_table = 'alttracker_altcustom'

    def __str__(self):
        return '%s - %s' % (self.alt.altName, self.alt.altRealm)


class AltProfession(models.Model):
    alt = models.ForeignKey(Alt, on_delete=models.CASCADE)

    class Profession(models.IntegerChoices):
        MISSING = 0, _('Missing')
        ALCHEMY = 171, _('Alchemy')
        BLACKSMITHING = 164, _('Blacksmithing')
        ENCHANTING = 333, _('Enchanting')
        ENGINEERING = 202, _('Engineering')
        INSCRIPTION = 773, _('Inscription')
        JEWELCRAFTING = 755, _('Jewelcrafting')
        LEATHERWORKING = 165, _('Leatherworking')
        TAILORING = 197, _('Tailoring')
        HERBALISM = 182, _('Herbalism')
        MINING = 186, _('Mining')
    profession = models.PositiveSmallIntegerField(choices=Profession.choices, default=Profession.MISSING)

    altProfessionExpiryDate = models.DateTimeField()
    professionData = models.JSONField()

    class Meta:
        db_table = 'alttracker_altprofession'
        constraints = [
            models.UniqueConstraint(fields=['alt', 'profession'], name='unique_profession')
        ]

    def __str__(self):
        return '%s - %s : %s' % (self.alt.altName, self.alt.altRealm, self.get_profession_display())


class AltAchievement(models.Model):
    alt = models.OneToOneField(Alt, on_delete=models.CASCADE, primary_key=True)
    altAchievementExpiryDate = models.DateTimeField()
    achievementData = models.JSONField()

    class Meta:
        db_table = 'alttracker_altachievement'

    def __str__(self):
        return '%s - %s' % (self.alt.altName, self.alt.altRealm)


class AltQuestCompleted(models.Model):
    alt = models.OneToOneField(Alt, on_delete=models.CASCADE, primary_key=True)
    altQuestCompletedExpiryDate = models.DateTimeField()
    questCompletedData = models.JSONField()

    class Meta:
        db_table = 'alttracker_altquestcompleted'

    def __str__(self):
        return '%s - %s' % (self.alt.altName, self.alt.altRealm)


class AltMedia(models.Model):
    alt = models.OneToOneField(Alt, on_delete=models.CASCADE, primary_key=True)
    altMediaExpiryDate = models.DateTimeField()
    avatar = models.CharField(max_length=100, default=None)
    inset = models.CharField(max_length=100, default=None)
    main = models.CharField(max_length=100, default=None)
    mainRaw = models.CharField(max_length=100, default=None)

    class Meta:
        db_table = 'alttracker_altmedia'

    def __str__(self):
        return '%s - %s' % (self.alt.altName, self.alt.altRealm)


class Equipment(models.Model):
    item_id = models.PositiveIntegerField(primary_key=True)
    name = models.CharField(max_length=80)
    # required_level = models.CharField(max_length=80)
    slot = models.CharField(max_length=20)
    # quality = models.CharField(max_length=20)
    armour_type = models.CharField(max_length=20)
    icon = models.CharField(max_length=100)

    class Meta:
        db_table = 'alttracker_equipment'

    def __str__(self):
        return '%s' % (self.name, self.slot)


class AltEquipment(models.Model):
    alt = models.ForeignKey(Alt, on_delete=models.CASCADE)
    equipment = models.ForeignKey(Equipment, on_delete=models.CASCADE)
    altEquipmentExpiryDate = models.DateTimeField()
    item_level = models.PositiveSmallIntegerField()
    stats = models.JSONField()
    slot = models.CharField(max_length=20)
    quality = models.CharField(max_length=20)
    sockets = models.JSONField()
    enchants = models.JSONField()
    spells = models.JSONField()
    azerite = models.JSONField()

    class Meta:
        db_table = 'alttracker_altequipment'

    def __str__(self):
        return '%s' % (self.alt.altName, self.slot)


######################################################################################
# NO LONGER USED

# class Requiem(models.Model):
#     # reqId = models.PositiveIntegerField(primary_key=True)
#     alt = models.OneToOneField(Alt, on_delete=models.CASCADE, primary_key=True)
#     # reqLevel = models.PositiveSmallIntegerField()
#     reqName = models.CharField(max_length=40)
#     reqRealm = models.CharField(max_length=40)
#     # class AltClass(models.TextChoices):
#     #   WARRIOR = 'Warrior'
#     #   PALADIN = 'Paladin'
#     #   HUNTER = 'Hunter'
#     #   ROGUE = 'Rogue'
#     #   PRIEST = 'Priest'
#     #   SHAMAN = 'Shaman'
#     #   MAGE = 'Mage'
#     #   WARLOCK = 'Warlock'
#     #   MONK = 'Monk'
#     #   DRUID = 'Druid'
#     #   DEMON_HUNTER = 'Demon Hunter'
#     #   DEATH_KNIGHT = 'Death Knight'
#     # reqClass = models.CharField(max_length=12,choices=AltClass.choices)
#     reqRank = models.PositiveSmallIntegerField()
#     reqExpiryDate = models.DateTimeField()

#     # class Meta:
#     #   unique_together = (("reqName","reqRealm"),)


# class Token(models.Model):
#     token = models.CharField(max_length=60)

######################################################################################

wowprof/templates/wowprof/wowprof_alts.html
{% extends "home/base.html" %}
{% block title %}WoWProf Alts
{% endblock %}
{% load static %}
{% load alttracker_filters %}
{% block content %}
<div>
    <h2  style="text-align: center">World of Warcraft - Alt Tracker</h2>
    <div class="row" style="margin: 15px">
        <div class="col-4">
            <a href="{% url 'wowprof_home' %}" class="btn btn-secondary">FazzTools Home</a>
            {% if request.session.altId %}
                <form method="post" style="display: inline-block">
                    {% csrf_token %}
                    <input type="submit" class="btn btn-secondary" id="alt-tracker-home-button" name="alt-tracker-home-button" value="Alt Tracker Home" />
                </form>
            {% else %}
                <a href="{% url 'wowprof_alts' %}" class="btn btn-secondary">Alt Tracker Home</a>
            {% endif %}
            <a href="{% url 'wowprof_checker' %}" class="btn btn-secondary">Alt Checker</a>
            <a href="{% url 'wowprof_weekly' %}" class="btn btn-secondary">Alt Weekly</a>
        </div>
        <div class="col-4" style="text-align: center">
            <form method="GET">
                <input type="hidden" name="format" value="csv">
                <input type="hidden" name="" value="">
                <input type="submit" value="Export to CSV" class="btn btn-secondary">
            </form>
        </div>
        <div class="col-4" style="text-align: right">
            {% if request.session.altId %}
                <form method="post" style="display: inline-block">
                    {% csrf_token %}
                    <input type="submit" class="btn btn-secondary" id="logout-button" name="logout-button" value="Logout" title="Log out of your battle.net account" />
                </form>
            {% else %}
                <form method="post" style="display: inline-block">
                    {% csrf_token %}
                    <input type="submit" class="btn btn-secondary" id="login-button" name="login-button" value="Login" title="Login to your battle.net account" />
                </form>
            {% endif %}
            <input class="btn btn-secondary" type="button" id="ajax-test" name="ajax-test" value="Refresh All" title="Refresh data for all characters" />
        </div>
    </div>
    <div class="row">
        <div class="col-12" style="text-align: center">
            <table id="alts-table" style="margin:auto; text-align:center">
                <colgroup>
                    <col span="5">
                    <col span="5" style="background-color:grey">
                </colgroup>
                <tr>
                    <th>#</th>
                    <th onclick="sortTableSpecial(1)"><img src="{% static 'wowprof/images/horde_alliance.png' %}" alt="Alliance and Horde faction logos" style="width:60px;height:30px"> <i class="fas fa-sort"></i></th>
                    <th>Level <i class="fas fa-sort"></i></th>
                    <th>Name <i class="fas fa-sort"></i></th>
                    <th>Realm <i class="fas fa-sort"></i></th>
                    <th>Class <i class="fas fa-sort"></i></th>
                    <th>Prof1 <i class="fas fa-sort"></i></th>
                    <th>Prof2 <i class="fas fa-sort"></i></th>
                    <th>Gear <i class="fas fa-sort"></i></th>
                    <th>Last Updated</th>
                    <th></th>
                </tr>
                {% for a in altData %}
                <tr>
                    <td>{{ a.index }}</td>
                    {% if a.altFaction == 'Alliance' %}
                        <td><img src="{% static 'wowprof/images/alliance.png' %}" alt="Alliance logo" style="width:30px;height:30px"></td>
                    {% else %}
                        <td><img src="{% static 'wowprof/images/horde.png' %}" alt="Horde logo" style="width:30px;height:30px"></td>
                    {% endif %}
                    <td>{{ a.altLevel }}</td>
                    <td>{{ a.altName }}</td>
                    <td>{{ a.altRealm }}</td>
                    <td>{{ a.get_altClass_display }}</td>
                    {% if a.altcustom.get_profession1_display == 'Missing' or not a.altcustom %}
                        <td><a>{{ a.altcustom.get_profession1_display }}</a></td>
                    {% else %}
                        <td><a href="{% url 'wowprof_alts_profession' name=a.altName|slug realm=a.altRealm|slug profession=a.altcustom.get_profession1_display|slug %}">{{ a.altcustom.get_profession1_display }}</a></td>
                    {% endif %}
                    {% if a.altcustom.get_profession2_display == 'Missing' or not a.altcustom %}
                        <td><a>{{ a.altcustom.get_profession2_display }}</a></td>
                    {% else %}
                        <td><a href="{% url 'wowprof_alts_profession' name=a.altName|slug realm=a.altRealm|slug profession=a.altcustom.get_profession2_display|slug %}">{{ a.altcustom.get_profession2_display }}</a></td>
                    {% endif %}
                    <td><a href="{% url 'wowprof_alts_more' name=a.altName|slug realm=a.altRealm|slug %}">{{ a.altcustom.average_item_level }}</a></td>
                    {% if not a.altcustom %}
                        <td>Not yet scanned</td>
                    {% else %}
                        <td>{{ a.altcustom.lastRefresh|datediff }}</td>
                    {% endif %}
                    <td><button><i class="fas fa-sync-alt"></i></button></td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</div>
{% endblock %}

wowprof/templates/wowprof/wowprof_alts_profession.html
{% extends "home/base.html" %}
{% block title %}WoWProf Alt Profession
{% endblock %}
{% load static %}
{% block content %}
<div>
    <h2 style="text-align: center">{{ alt.altName }} - {{ alt.altRealm }}<br />{{ profession.get_profession_display }}</h2>
    <div class="row">
        <a href="{% url 'wowprof_alts' %}" class="btn btn-secondary">Alt Tracker Home</a>
        <div class="col-12" style="text-align: center">
                {% for profession in profession.professionData %}
                <table class="alt-profession-table" style="margin:auto; text-align:left; margin-bottom:20px">
                <tr>
                    <th>ID</th>
                    <th>{{ profession.tier.name }}</th>
                    <th>{{ profession.skill_points }}/{{ profession.max_skill_points }}</th>
                </tr>
                    {% for recipe in profession.known_recipes %}
                    <tr>
                        <td>{{ recipe.id }}</td>
                        <td>{{ recipe.name }}</td>
                        <td><a href="https://www.wowhead.com/recipe/{{ recipe.id }}" target="_blank"><img src="{% static 'wowprof/images/wowheadlogo.png' %}" alt="WoWHead link" style="width:58px;height:40px"></a></td>
                    </tr>
                    {% endfor %}
                </table>
                {% endfor %}                
        </div>
    </div>
</div>
{% endblock %}

wowprof/templates/wowprof/wowprof_alts_weekly.html
{% extends "home/base.html" %}
{% block title %}WoWProf Alts
{% endblock %}
{% load static %}
{% load alttracker_filters %}
{% block content %}
<div>
    <h2 style="text-align: center">World of Warcraft - Weekly</h2>
    <div class="row" style="margin: 15px">
        <div class="col-4">
            <a href="{% url 'wowprof_home' %}" class="btn btn-secondary">FazzTools Home</a>
            {% if request.session.altId %}
                <form method="post" style="display: inline-block">
                    {% csrf_token %}
                    <input type="submit" class="btn btn-secondary" id="alt-tracker-home-button-checker" name="alt-tracker-home-button-checker" value="Alt Tracker Home" />
                </form>
            {% else %}
                <a href="{% url 'wowprof_alts' %}" class="btn btn-secondary">Alt Tracker Home</a>
            {% endif %}
        </div>
        <div class="col-4" style="text-align: center">
            <form method="GET">
                <input type="hidden" name="format" value="csv">
                <input type="hidden" name="" value="">
                <input type="submit" value="Export to CSV" class="btn btn-secondary">
            </form>
        </div>
        <div class="col-4">

        </div>
    </div>
    <div class="row">
        <div class="col-12" style="text-align: center">
            <table id="alts-checker-table" style="margin:auto; text-align:center">
                <tr>
                    <th>#</th>
                    <th onclick="sortTableChecker(1)"><img src="{% static 'wowprof/images/horde_alliance.png' %}" alt="Alliance and Horde faction logos" style="width:60px;height:30px"> <i class="fas fa-sort"></i></th>
                    <th>Level <i class="fas fa-sort"></i></th>
                    <th>Name <i class="fas fa-sort"></i></th>
                    <th>Realm <i class="fas fa-sort"></i></th>
                    <th>Class <i class="fas fa-sort"></i></th>
                    <th>Mount <i class="fas fa-sort"></th>
                    <th>Garrison <i class="fas fa-sort"></th>
                    <th>MT <i class="fas fa-sort"></th>
                    <th>SM <i class="fas fa-sort"></th>
                    <th>Location <i class="fas fa-sort"></i></th>
                    <th>Gold <i class="fas fa-sort"></i></th>
                </tr>
                {% for a in altData %}
                <tr>
                    <td>{{ a.index }}</td>
                    {% if a.altFaction == 'Alliance' %}
                        <td><img src="{% static 'wowprof/images/alliance.png' %}" alt="Alliance logo" style="width:30px;height:30px"></td>
                    {% else %}
                        <td><img src="{% static 'wowprof/images/horde.png' %}" alt="Horde logo" style="width:30px;height:30px"></td>
                    {% endif %}
                    <td>{{ a.altLevel }}</td>
                    <td>{{ a.altName }}</td>
                    <td>{{ a.altRealm }}</td>
                    <td>{{ a.get_altClass_display }}</td>
                    <td>{{ a.altcustom.get_mount_display }}</td>
                    <td>{{ a.altcustom.get_garrison_display }}</td>
                    <td>{{ a.altcustom.get_mageTower_display }}</td>
                    <td>{{ a.altcustom.get_shadowmourne_display }}</td>
                    <td>{{ a.altcustom.location }}</td>
                    <td>{{ a.altcustom.gold|goldcount }}</td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</div>
{% endblock %}

wowprof/templates/wowprof/wowprof_checker.html
{% extends "home/base.html" %}
{% block title %}WoWProf Alts
{% endblock %}
{% load static %}
{% load alttracker_filters %}
{% block content %}
<div>
    <h2 style="text-align: center">World of Warcraft - Checker</h2>
    <div class="row" style="margin: 15px">
        <div class="col-4">
            <a href="{% url 'wowprof_home' %}" class="btn btn-secondary">FazzTools Home</a>
            {% if request.session.altId %}
                <form method="post" style="display: inline-block">
                    {% csrf_token %}
                    <input type="submit" class="btn btn-secondary" id="alt-tracker-home-button-checker" name="alt-tracker-home-button-checker" value="Alt Tracker Home" />
                </form>
            {% else %}
                <a href="{% url 'wowprof_alts' %}" class="btn btn-secondary">Alt Tracker Home</a>
            {% endif %}
        </div>
        <div class="col-4" style="text-align: center">
            <form method="GET">
                <input type="hidden" name="format" value="csv">
                <input type="hidden" name="" value="">
                <input type="submit" value="Export to CSV" class="btn btn-secondary">
            </form>
        </div>
        <div class="col-4">

        </div>
    </div>
    <div class="row">
        <div class="col-12" style="text-align: center">
            <table id="alts-checker-table" style="margin:auto; text-align:center">
                <tr>
                    <th>#</th>
                    <th onclick="sortTableChecker(1)"><img src="{% static 'wowprof/images/horde_alliance.png' %}" alt="Alliance and Horde faction logos" style="width:60px;height:30px"> <i class="fas fa-sort"></i></th>
                    <th>Level <i class="fas fa-sort"></i></th>
                    <th>Name <i class="fas fa-sort"></i></th>
                    <th>Realm <i class="fas fa-sort"></i></th>
                    <th>Class <i class="fas fa-sort"></i></th>
                    <th>Mount <i class="fas fa-sort"></th>
                    <th>Garrison <i class="fas fa-sort"></th>
                    <th>MT <i class="fas fa-sort"></th>
                    <th>SM <i class="fas fa-sort"></th>
                    <th>Location <i class="fas fa-sort"></i></th>
                    <th>Gold <i class="fas fa-sort"></i></th>
                </tr>
                {% for a in altData %}
                <tr>
                    <td>{{ a.index }}</td>
                    {% if a.altFaction == 'Alliance' %}
                        <td><img src="{% static 'wowprof/images/alliance.png' %}" alt="Alliance logo" style="width:30px;height:30px"></td>
                    {% else %}
                        <td><img src="{% static 'wowprof/images/horde.png' %}" alt="Horde logo" style="width:30px;height:30px"></td>
                    {% endif %}
                    <td>{{ a.altLevel }}</td>
                    <td>{{ a.altName }}</td>
                    <td>{{ a.altRealm }}</td>
                    <td>{{ a.get_altClass_display }}</td>
                    <td>{{ a.altcustom.get_mount_display }}</td>
                    <td>{{ a.altcustom.get_garrison_display }}</td>
                    <td>{{ a.altcustom.get_mageTower_display }}</td>
                    <td>{{ a.altcustom.get_shadowmourne_display }}</td>
                    <td>{{ a.altcustom.location }}</td>
                    <td>{{ a.altcustom.gold|goldcount }}</td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</div>
{% endblock %}

wowprof/templates/wowprof/wowprof_home.html
{% extends "home/base.html" %}
{% block title %}FazzTools Home
{% endblock %}
{% block content %}
<div>
    <h2  style="text-align: center">Fazz Tools Home</h2>
    <div class="row">
        <div class="col-4" style="text-align: center">
            {% if request.session.altId %}
                <form method="post" style="display: inline-block">
                    {% csrf_token %}
                    <input type="submit" class="btn btn-secondary" id="alt-tracker-button" name="alt-tracker-button" value="Alt Tracker" />
                </form>
            {% else %}
                <a href="{% url 'wowprof_alts' %}" class="btn btn-secondary">Alt Tracker</a>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}